### ISSUE TITLE
broken lessons

### ISSUE THREAD

**Issue by Davidkeebler** [learn-co-curriculum/dsc-implementing-recommender-systems-lab#2]
## Link to Canvas

https://learning.flatironschool.com/courses/6486/assignments/243690?module_item_id=573635
https://learning.flatironschool.com/courses/6486/pages/implementing-recommendation-engines-with-surprise?module_item_id=609914

## Issue Subtype

- [x ] Master branch code
- [x ] Solution branch code
- [ ] Code tests
- [ ] Layout/rendering issue
- [ x] Instructions unclear
- [ x] Other (explain below)

### Source

```

```

### Concern

The jester dataset is not already loaded into the notebook and will not download from the source website, so the Implementing Recommendation Engines with Surprise lesson will not run. 
The Implementing Recommender Systems - Lab lesson cannot be completed because of an error with a deprecated numpy alias that is causing an error when trying to cross validate with knn basic. The instructions are also unclear as the parameters that should be used in the grid search were never explained in any lesson and the documentation alone is not enough to understand which parameters should be selected for this task without the guidance of an instructor.

## What OS Are You Using?

- [ ] OS X
- [ ] Windows
- [ ] WSL
- [ ] Linux
- [ ] Saturn Cloud from Canvas

**Comment by bpurdy-ds** [comment]
@Davidkeebler I replicated the error with the lesson and the lab. They appear to be the same error where when `predict()` or `cross_validate` are run on the knn, it gives the `np.int` error. 
We'll investigate and get it fixed, but with Thanksgiving next week, we may not be able to close these two issues until the week after.

**Comment by bpurdy-ds** [comment]
@Davidkeebler We haven't forgotten about you, still working on it. Thanks for your patience.

**Comment by bpurdy-ds** [comment]
This is fixed. We need new SC images to that the `scikit-surprise` would work correctly. Thus, both the lesson and the lab have new SC links and work. Thanks again for drawing this to our attention.
